import type { TemaConfig } from "./tema-config";

const konjunktur: TemaConfig = {
  temaId: "konjunktur",
  temaNamn: "Konjunktur",
  temaFarg: "bla",
  kortNamn: {
    K_SYSS_INR: "Inrikes födda",
    K_SYSS_UTR: "Utrikes födda",
    K_SYSS_KV: "Kvinnor",
    K_SYSS_MAN: "Män",
    K_ARBL_INR: "Inrikes födda",
    K_ARBL_UTR: "Utrikes födda",
    K_ARBL_KV: "Kvinnor",
    K_ARBL_MAN: "Män",
    K_ARKR_KV: "Kvinnor",
    K_ARKR_MAN: "Män",
    K_DAG_JORD: "Jordbruk m.m.",
    K_DAG_IND: "Tillverkning",
    K_DAG_ENMI: "Energi & miljö",
    K_DAG_BYG: "Bygg",
    K_DAG_HAND: "Handel",
    K_DAG_TRANS: "Transport",
    K_DAG_HOTEL: "Hotell & rest.",
    K_DAG_IT: "IT & komm.",
    K_DAG_FINANS: "Finans",
    K_DAG_FAST: "Fastigheter",
    K_DAG_FORETJ: "Företagstjänster",
    K_DAG_OFF: "Offentlig sektor",
    K_DAG_KULT: "Kultur m.m.",
  },
  sektioner: [
    {
      id: "sysselsattning",
      namn: "Sysselsättningsgrad 20–64 år (prelim.)",
      kpiIds: ["K_SYSS_TOT"],
      undersektioner: [
        { namn: "Födelseregion", kpiIds: ["K_SYSS_INR", "K_SYSS_UTR"] },
        { namn: "Kvinnor och män", kpiIds: ["K_SYSS_KV", "K_SYSS_MAN"] },
      ],
    },
    {
      id: "arbetsloshet",
      namn: "Arbetslöshet 20–64 år (prelim.)",
      kpiIds: ["K_ARBL_TOT"],
      undersektioner: [
        { namn: "Födelseregion", kpiIds: ["K_ARBL_INR", "K_ARBL_UTR"] },
        { namn: "Kvinnor och män", kpiIds: ["K_ARBL_KV", "K_ARBL_MAN"] },
      ],
    },
    {
      id: "arbetskraft",
      namn: "Arbetskraftsdeltagande 20–64 år (prelim.)",
      kpiIds: ["K_ARKR_TOT"],
      undersektioner: [
        { namn: "Kvinnor och män", kpiIds: ["K_ARKR_KV", "K_ARKR_MAN"] },
      ],
    },
    {
      id: "dagbefolkning",
      namn: "Sysselsatta dagbefolkning (prelim.)",
      kpiIds: ["K_DAG_TOT"],
      undersektioner: [
        {
          namn: "Branscher",
          kpiIds: [
            "K_DAG_JORD",
            "K_DAG_IND",
            "K_DAG_ENMI",
            "K_DAG_BYG",
            "K_DAG_HAND",
            "K_DAG_TRANS",
            "K_DAG_HOTEL",
            "K_DAG_IT",
            "K_DAG_FINANS",
            "K_DAG_FAST",
            "K_DAG_FORETJ",
            "K_DAG_OFF",
            "K_DAG_KULT",
          ],
        },
      ],
    },
    {
      id: "forandring",
      namn: "Förändring mot samma månad föregående år",
      kpiIds: ["K_SYSS_FORANDR", "K_ARBL_FORANDR", "K_DAG_TILLVAXT"],
    },
  ],
  visningsnamn: {
    K_SYSS_TOT: "Sysselsättningsgrad (prelim.)",
    K_SYSS_ANT: "Antal sysselsatta (prelim.)",
    K_SYSS_INR: "Sysselsättningsgrad, inrikes födda (prelim.)",
    K_SYSS_UTR: "Sysselsättningsgrad, utrikes födda (prelim.)",
    K_SYSS_KV: "Sysselsättningsgrad, kvinnor (prelim.)",
    K_SYSS_MAN: "Sysselsättningsgrad, män (prelim.)",

    K_ARBL_TOT: "Arbetslöshetsgrad (prelim.)",
    K_ARBL_ANT: "Antal arbetslösa (prelim.)",
    K_ARBL_INR: "Arbetslöshetsgrad, inrikes födda (prelim.)",
    K_ARBL_UTR: "Arbetslöshetsgrad, utrikes födda (prelim.)",
    K_ARBL_KV: "Arbetslöshetsgrad, kvinnor (prelim.)",
    K_ARBL_MAN: "Arbetslöshetsgrad, män (prelim.)",

    K_ARKR_TOT: "Arbetskraftsdeltagande (prelim.)",
    K_ARKR_KV: "Arbetskraftsdeltagande, kvinnor (prelim.)",
    K_ARKR_MAN: "Arbetskraftsdeltagande, män (prelim.)",

    K_DAG_TOT: "Sysselsatta dagbefolkning, totalt (prelim.)",
    K_DAG_JORD: "Sysselsatta, jordbruk m.m. (prelim.)",
    K_DAG_IND: "Sysselsatta, tillverkning (prelim.)",
    K_DAG_ENMI: "Sysselsatta, energi och miljö (prelim.)",
    K_DAG_BYG: "Sysselsatta, bygg (prelim.)",
    K_DAG_HAND: "Sysselsatta, handel (prelim.)",
    K_DAG_TRANS: "Sysselsatta, transport (prelim.)",
    K_DAG_HOTEL: "Sysselsatta, hotell & restaurang (prelim.)",
    K_DAG_IT: "Sysselsatta, IT och kommunikation (prelim.)",
    K_DAG_FINANS: "Sysselsatta, finans och försäkring (prelim.)",
    K_DAG_FAST: "Sysselsatta, fastigheter (prelim.)",
    K_DAG_FORETJ: "Sysselsatta, företagstjänster (prelim.)",
    K_DAG_OFF: "Sysselsatta, offentlig sektor (prelim.)",
    K_DAG_KULT: "Sysselsatta, kultur m.m. (prelim.)",

    K_SYSS_FORANDR: "Sysselsättningsgrad, årsförändring (procentenheter)",
    K_ARBL_FORANDR: "Arbetslöshet, årsförändring (procentenheter)",
    K_DAG_TILLVAXT: "Dagbefolkning, årsförändring (procent)",
  },
};

export default konjunktur;
