import type { TemaConfig } from "./tema-config";

const naringsliv: TemaConfig = {
  temaId: "naringsliv",
  temaNamn: "Näringsliv",
  temaFarg: "rod",
  sektioner: [
    // Sektorer — uppdelade i enskilda kort med egna expand
    {
      id: "sektor-tot",
      namn: "Dagbefolkning totalt",
      kpiIds: ["N_SEK_TOT"],
      undersektioner: [
        { namn: "Kön", kpiIds: ["N_SEK_TOT_KV", "N_SEK_TOT_MAN"] },
        { namn: "Födelseregion", kpiIds: ["N_SEK_TOT_INR", "N_SEK_TOT_UTR"] },
      ],
    },
    {
      id: "sektor-naring",
      namn: "Näringslivet",
      kpiIds: ["N_SEK_NARING"],
      undersektioner: [
        { namn: "Kön", kpiIds: ["N_SEK_NARING_KV", "N_SEK_NARING_MAN"] },
        { namn: "Födelseregion", kpiIds: ["N_SEK_NARING_INR", "N_SEK_NARING_UTR"] },
      ],
    },
    {
      id: "sektor-off",
      namn: "Offentlig sektor",
      kpiIds: ["N_SEK_OFF"],
      undersektioner: [
        { namn: "Kön", kpiIds: ["N_SEK_OFF_KV", "N_SEK_OFF_MAN"] },
        { namn: "Födelseregion", kpiIds: ["N_SEK_OFF_INR", "N_SEK_OFF_UTR"] },
      ],
    },
    // Tillväxt
    {
      id: "tillvaxt-tot",
      namn: "Tillväxt totalt",
      kpiIds: ["N_SEK_TOT_TILLV"],
      undersektioner: [
        { namn: "Kön", kpiIds: ["N_SEK_TOT_KV_TILLV", "N_SEK_TOT_MAN_TILLV"] },
        { namn: "Födelseregion", kpiIds: ["N_SEK_TOT_INR_TILLV", "N_SEK_TOT_UTR_TILLV"] },
      ],
    },
    {
      id: "tillvaxt-naring",
      namn: "Tillväxt näringslivet",
      kpiIds: ["N_SEK_NARING_TILLV"],
      undersektioner: [
        { namn: "Kön", kpiIds: ["N_SEK_NARING_KV_TILLV", "N_SEK_NARING_MAN_TILLV"] },
        { namn: "Födelseregion", kpiIds: ["N_SEK_NARING_INR_TILLV", "N_SEK_NARING_UTR_TILLV"] },
      ],
    },
    {
      id: "tillvaxt-off",
      namn: "Tillväxt offentlig sektor",
      kpiIds: ["N_SEK_OFF_TILLV"],
      undersektioner: [
        { namn: "Kön", kpiIds: ["N_SEK_OFF_KV_TILLV", "N_SEK_OFF_MAN_TILLV"] },
        { namn: "Födelseregion", kpiIds: ["N_SEK_OFF_INR_TILLV", "N_SEK_OFF_UTR_TILLV"] },
      ],
    },
    // Branscher — flat grid av kort
    {
      id: "bransch",
      namn: "Branscher",
      sorteraEfterVarde: true,
      kpiIds: [
        "N_BR_A_A", "N_BR_BC_A", "N_BR_DE_A", "N_BR_F_A",
        "N_BR_G_A", "N_BR_H_A", "N_BR_I_A", "N_BR_J_A",
        "N_BR_K_A", "N_BR_L_A", "N_BR_MN_A", "N_BR_O_A",
        "N_BR_P_A", "N_BR_Q_A", "N_BR_RSTU_A",
      ],
    },
    // Utbildningsnivå
    {
      id: "utbildningsniva",
      namn: "Utbildningsnivå",
      kpiIds: ["N_UTB_FORGYM_A", "N_UTB_GYM_A", "N_UTB_EFTGYM_A"],
    },
    // Yrkesställning — uppdelade
    {
      id: "yrk-anst",
      namn: "Anställda",
      kpiIds: ["N_YRK_ANST_A"],
      undersektioner: [
        { namn: "Födelseregion", kpiIds: ["N_YRK_ANST_INR_A", "N_YRK_ANST_UTR_A"] },
        { namn: "Könsfördelning", kpiIds: ["N_YRK_ANST_KV_A"] },
      ],
    },
    {
      id: "yrk-ab",
      namn: "Företagare i AB",
      kpiIds: ["N_YRK_EGAB_A"],
      undersektioner: [
        { namn: "Födelseregion", kpiIds: ["N_YRK_EGAB_INR_A", "N_YRK_EGAB_UTR_A"] },
        { namn: "Könsfördelning", kpiIds: ["N_YRK_EGAB_KV_A"] },
      ],
    },
    {
      id: "yrk-egen",
      namn: "Egenföretagare",
      kpiIds: ["N_YRK_EGFOR_A"],
      undersektioner: [
        { namn: "Födelseregion", kpiIds: ["N_YRK_EGFOR_INR_A", "N_YRK_EGFOR_UTR_A"] },
        { namn: "Könsfördelning", kpiIds: ["N_YRK_EGFOR_KV_A"] },
      ],
    },
    // Nyföretagande
    {
      id: "foretagande",
      namn: "Nyföretagande",
      kpiIds: ["N00999", "N45700"],
    },
  ],
  kortNamn: {
    // Branscher
    "N_BR_A_A": "Jordbruk & skog",
    "N_BR_BC_A": "Tillverkning",
    "N_BR_DE_A": "Energi & miljö",
    "N_BR_F_A": "Bygg",
    "N_BR_G_A": "Handel",
    "N_BR_H_A": "Transport",
    "N_BR_I_A": "Hotell & restaurang",
    "N_BR_J_A": "IT & kommunikation",
    "N_BR_K_A": "Finans & försäkring",
    "N_BR_L_A": "Fastighet",
    "N_BR_MN_A": "Företagstjänster",
    "N_BR_O_A": "Offentlig förvaltning",
    "N_BR_P_A": "Utbildning",
    "N_BR_Q_A": "Vård & omsorg",
    "N_BR_RSTU_A": "Övriga tjänster",
    // Utbildningsnivå
    "N_UTB_FORGYM_A": "Förgymnasial",
    "N_UTB_GYM_A": "Gymnasial",
    "N_UTB_EFTGYM_A": "Eftergymnasial",
    // Nyföretagande
    "N00999": "Nystartade företag",
    "N45700": "Företagsförekomster",
    // Expand-kortnamn
    "N_SEK_TOT_KV": "Kvinnor",
    "N_SEK_TOT_MAN": "Män",
    "N_SEK_TOT_INR": "Inrikes födda",
    "N_SEK_TOT_UTR": "Utrikes födda",
    "N_SEK_NARING_KV": "Kvinnor",
    "N_SEK_NARING_MAN": "Män",
    "N_SEK_NARING_INR": "Inrikes födda",
    "N_SEK_NARING_UTR": "Utrikes födda",
    "N_SEK_OFF_KV": "Kvinnor",
    "N_SEK_OFF_MAN": "Män",
    "N_SEK_OFF_INR": "Inrikes födda",
    "N_SEK_OFF_UTR": "Utrikes födda",
    "N_YRK_ANST_INR_A": "Inrikes födda",
    "N_YRK_ANST_UTR_A": "Utrikes födda",
    "N_YRK_ANST_KV_A": "Andel kvinnor",
    "N_YRK_EGAB_INR_A": "Inrikes födda",
    "N_YRK_EGAB_UTR_A": "Utrikes födda",
    "N_YRK_EGAB_KV_A": "Andel kvinnor",
    "N_YRK_EGFOR_INR_A": "Inrikes födda",
    "N_YRK_EGFOR_UTR_A": "Utrikes födda",
    "N_YRK_EGFOR_KV_A": "Andel kvinnor",
  },
  visningsnamn: {
    // Sektor
    "N_SEK_TOT": "Förvärvsarbetande dagbefolkning 15–74 år, antal",
    "N_SEK_NARING": "Förvärvsarbetande i näringslivet 15–74 år, antal",
    "N_SEK_NARING_A": "Förvärvsarbetande i näringslivet 15–74 år, andel (%)",
    "N_SEK_OFF": "Förvärvsarbetande i offentlig sektor 15–74 år, antal",
    "N_SEK_OFF_A": "Förvärvsarbetande i offentlig sektor 15–74 år, andel (%)",
    "N_SEK_TOT_KV": "Förvärvsarbetande kvinnor 15–74 år, antal",
    "N_SEK_TOT_MAN": "Förvärvsarbetande män 15–74 år, antal",
    "N_SEK_NARING_KV": "Förvärvsarbetande kvinnor i näringslivet 15–74 år, antal",
    "N_SEK_NARING_MAN": "Förvärvsarbetande män i näringslivet 15–74 år, antal",
    "N_SEK_OFF_KV": "Förvärvsarbetande kvinnor i offentlig sektor 15–74 år, antal",
    "N_SEK_OFF_MAN": "Förvärvsarbetande män i offentlig sektor 15–74 år, antal",
    "N_SEK_TOT_INR": "Förvärvsarbetande inrikes födda 15–74 år, antal",
    "N_SEK_TOT_UTR": "Förvärvsarbetande utrikes födda 15–74 år, antal",
    "N_SEK_NARING_INR": "Förvärvsarbetande inrikes födda i näringslivet 15–74 år, antal",
    "N_SEK_NARING_UTR": "Förvärvsarbetande utrikes födda i näringslivet 15–74 år, antal",
    "N_SEK_OFF_INR": "Förvärvsarbetande inrikes födda i offentlig sektor 15–74 år, antal",
    "N_SEK_OFF_UTR": "Förvärvsarbetande utrikes födda i offentlig sektor 15–74 år, antal",
    // Tillväxt
    "N_SEK_TOT_TILLV": "Årlig tillväxt, förvärvsarbetande totalt, förändring (%)",
    "N_SEK_NARING_TILLV": "Årlig tillväxt, förvärvsarbetande i näringslivet, förändring (%)",
    "N_SEK_OFF_TILLV": "Årlig tillväxt, förvärvsarbetande i offentlig sektor, förändring (%)",
    "N_SEK_TOT_KV_TILLV": "Årlig tillväxt, förvärvsarbetande kvinnor, förändring (%)",
    "N_SEK_TOT_MAN_TILLV": "Årlig tillväxt, förvärvsarbetande män, förändring (%)",
    "N_SEK_NARING_KV_TILLV": "Årlig tillväxt, kvinnor i näringslivet, förändring (%)",
    "N_SEK_NARING_MAN_TILLV": "Årlig tillväxt, män i näringslivet, förändring (%)",
    "N_SEK_OFF_KV_TILLV": "Årlig tillväxt, kvinnor i offentlig sektor, förändring (%)",
    "N_SEK_OFF_MAN_TILLV": "Årlig tillväxt, män i offentlig sektor, förändring (%)",
    "N_SEK_TOT_INR_TILLV": "Årlig tillväxt, förvärvsarbetande inrikes födda, förändring (%)",
    "N_SEK_TOT_UTR_TILLV": "Årlig tillväxt, förvärvsarbetande utrikes födda, förändring (%)",
    "N_SEK_NARING_INR_TILLV": "Årlig tillväxt, inrikes födda i näringslivet, förändring (%)",
    "N_SEK_NARING_UTR_TILLV": "Årlig tillväxt, utrikes födda i näringslivet, förändring (%)",
    "N_SEK_OFF_INR_TILLV": "Årlig tillväxt, inrikes födda i offentlig sektor, förändring (%)",
    "N_SEK_OFF_UTR_TILLV": "Årlig tillväxt, utrikes födda i offentlig sektor, förändring (%)",
    // Branscher
    "N_BR_A_A": "Förvärvsarbetande inom jordbruk och skogsbruk, andel (%)",
    "N_BR_A": "Förvärvsarbetande inom jordbruk och skogsbruk, antal",
    "N_BR_BC_A": "Förvärvsarbetande inom tillverkning, andel (%)",
    "N_BR_BC": "Förvärvsarbetande inom tillverkning, antal",
    "N_BR_DE_A": "Förvärvsarbetande inom energi och miljö, andel (%)",
    "N_BR_DE": "Förvärvsarbetande inom energi och miljö, antal",
    "N_BR_F_A": "Förvärvsarbetande inom byggverksamhet, andel (%)",
    "N_BR_F": "Förvärvsarbetande inom byggverksamhet, antal",
    "N_BR_G_A": "Förvärvsarbetande inom handel, andel (%)",
    "N_BR_G": "Förvärvsarbetande inom handel, antal",
    "N_BR_H_A": "Förvärvsarbetande inom transport, andel (%)",
    "N_BR_H": "Förvärvsarbetande inom transport, antal",
    "N_BR_I_A": "Förvärvsarbetande inom hotell och restaurang, andel (%)",
    "N_BR_I": "Förvärvsarbetande inom hotell och restaurang, antal",
    "N_BR_J_A": "Förvärvsarbetande inom IT och kommunikation, andel (%)",
    "N_BR_J": "Förvärvsarbetande inom IT och kommunikation, antal",
    "N_BR_K_A": "Förvärvsarbetande inom finans och försäkring, andel (%)",
    "N_BR_K": "Förvärvsarbetande inom finans och försäkring, antal",
    "N_BR_L_A": "Förvärvsarbetande inom fastighetsverksamhet, andel (%)",
    "N_BR_L": "Förvärvsarbetande inom fastighetsverksamhet, antal",
    "N_BR_MN_A": "Förvärvsarbetande inom företagstjänster, andel (%)",
    "N_BR_MN": "Förvärvsarbetande inom företagstjänster, antal",
    "N_BR_O_A": "Förvärvsarbetande inom offentlig förvaltning, andel (%)",
    "N_BR_O": "Förvärvsarbetande inom offentlig förvaltning, antal",
    "N_BR_P_A": "Förvärvsarbetande inom utbildning, andel (%)",
    "N_BR_P": "Förvärvsarbetande inom utbildning, antal",
    "N_BR_Q_A": "Förvärvsarbetande inom vård och omsorg, andel (%)",
    "N_BR_Q": "Förvärvsarbetande inom vård och omsorg, antal",
    "N_BR_RSTU_A": "Förvärvsarbetande inom övriga tjänster, andel (%)",
    "N_BR_RSTU": "Förvärvsarbetande inom övriga tjänster, antal",
    // Utbildningsnivå
    "N_UTB_FORGYM_A": "Förvärvsarbetande med förgymnasial utbildning, andel (%)",
    "N_UTB_FORGYM": "Förvärvsarbetande med förgymnasial utbildning, antal",
    "N_UTB_GYM_A": "Förvärvsarbetande med gymnasial utbildning, andel (%)",
    "N_UTB_GYM": "Förvärvsarbetande med gymnasial utbildning, antal",
    "N_UTB_EFTGYM_A": "Förvärvsarbetande med eftergymnasial utbildning, andel (%)",
    "N_UTB_EFTGYM": "Förvärvsarbetande med eftergymnasial utbildning, antal",
    // Yrkesställning
    "N_YRK_ANST_A": "Anställda bland förvärvsarbetande 15–74 år, andel (%)",
    "N_YRK_ANST": "Anställda bland förvärvsarbetande 15–74 år, antal",
    "N_YRK_EGAB_A": "Företagare i AB bland förvärvsarbetande 15–74 år, andel (%)",
    "N_YRK_EGAB": "Företagare i AB bland förvärvsarbetande 15–74 år, antal",
    "N_YRK_EGFOR_A": "Egenföretagare bland förvärvsarbetande 15–74 år, andel (%)",
    "N_YRK_EGFOR": "Egenföretagare bland förvärvsarbetande 15–74 år, antal",
    "N_YRK_ANST_INR_A": "Anställda bland inrikes födda 15–74 år, andel (%)",
    "N_YRK_ANST_INR": "Anställda bland inrikes födda 15–74 år, antal",
    "N_YRK_ANST_UTR_A": "Anställda bland utrikes födda 15–74 år, andel (%)",
    "N_YRK_ANST_UTR": "Anställda bland utrikes födda 15–74 år, antal",
    "N_YRK_EGAB_INR_A": "Företagare i AB bland inrikes födda, andel (%)",
    "N_YRK_EGAB_INR": "Företagare i AB bland inrikes födda, antal",
    "N_YRK_EGAB_UTR_A": "Företagare i AB bland utrikes födda, andel (%)",
    "N_YRK_EGAB_UTR": "Företagare i AB bland utrikes födda, antal",
    "N_YRK_EGFOR_INR_A": "Egenföretagare bland inrikes födda, andel (%)",
    "N_YRK_EGFOR_INR": "Egenföretagare bland inrikes födda, antal",
    "N_YRK_EGFOR_UTR_A": "Egenföretagare bland utrikes födda, andel (%)",
    "N_YRK_EGFOR_UTR": "Egenföretagare bland utrikes födda, antal",
    "N_YRK_ANST_KV_A": "Andel kvinnor bland anställda 15–74 år (%)",
    "N_YRK_ANST_KV": "Antal kvinnor bland anställda 15–74 år",
    "N_YRK_EGAB_KV_A": "Andel kvinnor bland företagare i AB (%)",
    "N_YRK_EGAB_KV": "Antal kvinnor bland företagare i AB",
    "N_YRK_EGFOR_KV_A": "Andel kvinnor bland egenföretagare (%)",
    "N_YRK_EGFOR_KV": "Antal kvinnor bland egenföretagare",
    // Kolada
    "N00999": "Nystartade företag per 1 000 invånare",
    "N01003": "Nystartade företag, antal",
    "N45700": "Antal företagsförekomster per 1 000 invånare",
  },
};

export default naringsliv;
